# Generated by Django 2.0.8 on 2018-08-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('color', models.CharField(choices=[('0', 'Blanco'), ('1', 'Negro'), ('2', 'Rojo'), ('3', 'Amarillo'), ('4', 'Azul')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='deposito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionapp.Deposito'),
        ),
    ]
