# Generated by Django 2.0.8 on 2018-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0006_auto_20180906_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='anulado',
            field=models.IntegerField(default=0),
        ),
    ]
